workrequest/config/routes.rb
Workrequest::Application.routes.draw do
  resources :companies

  resources :supports

  resources :work_requests

  resources :profiles

  get "welcome/index"

  devise_for :users

  resources :lookups

  root :to => 'welcome#index'

end

workrequest/app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :title

  default_scope order('title asc')
end

workrequest/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
  
end

workrequest/app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name
  default_scope order('name asc')

  has_many :profiles
  has_many :workrequests
  has_many :supports
end

workrequest/app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :lookup_key, :lookup_name, :lookup_value
end

workrequest/app/models/plant.rb
class Plant < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
  
end

workrequest/app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname, :company_id
  default_scope order('firstname asc')

  has_many :workrequests
  has_many :supports
  belongs_to :company

  scope :by_email, lambda {|email| where('email=?',email)}

  validates :email, :uniqueness => true
end

workrequest/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
end

workrequest/app/models/support.rb
class Support < ActiveRecord::Base
  attr_accessible :assignedto_id, :businessunit_id, :category_id, :created_by, :description, :plant_id, :queue, :status_id, :title, :workrequest_id
  has_one :businessunit
  has_one :category
  has_one :plant
  has_one :status
  has_one :workrequest
end

workrequest/app/models/support_comment.rb
class SupportComment < ActiveRecord::Base
  attr_accessible :comment, :support_id
end

workrequest/app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :title

  has_many :workrequests
  has_many :supports
end

workrequest/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

workrequest/app/models/work_request.rb
class WorkRequest < ActiveRecord::Base
  attr_accessible :area_id, :category_id, :plant_id, :queue, :requestors, :status_id, :title, :created_by, :unit_id, :company_id, :profile_id

  belongs_to :category
  belongs_to :area
  belongs_to :unit
  belongs_to :plant
  belongs_to :status
  belongs_to :company
  belongs_to :profile

  validates :title, :presence => true
  validates :area_id, :presence => true
  validates :unit_id, :presence => true
  validates :category_id, :presence => true
  validates :plant_id, :presence => true
  validates :status_id, :presence => true
  validates :requestors, :presence => true

  scope :by_company_id, lambda { |company_id| where('company_id=?', company_id)}

end

workrequest/app/models/work_request_comment.rb
class WorkRequestComment < ActiveRecord::Base
  attr_accessible :comment, :workrequest_id
end

workrequest/app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lookups }
    end
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/new
  # GET /lookups/new.json
  def new
    @lookup = Lookup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/1/edit
  def edit
    @lookup = Lookup.find(params[:id])
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(params[:lookup])

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render json: @lookup, status: :created, location: @lookup }
      else
        format.html { render action: "new" }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lookups/1
  # PUT /lookups/1.json
  def update
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      if @lookup.update_attributes(params[:lookup])
        format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup = Lookup.find(params[:id])
    @lookup.destroy

    respond_to do |format|
      format.html { redirect_to lookups_url }
      format.json { head :no_content }
    end
  end
end

workrequest/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])

    if @profile.email != current_user.email
      redirect_to root_url
    end

    if @profile.nil?
      redirect_to :action=>"new"
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

workrequest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
  		@profile = Profile.by_email(current_user.email).first
  		if @profile == nil
  			@profile = Profile.new
  			@profile.email = current_user.email
  			@profile.save
  		end
  	end
  end
end

workrequest/app/helpers/application_helper.rb
module ApplicationHelper
end

workrequest/app/helpers/companies_helper.rb
module CompaniesHelper
end

workrequest/app/helpers/lookups_helper.rb
module LookupsHelper
end

workrequest/app/helpers/profiles_helper.rb
module ProfilesHelper
end

workrequest/app/helpers/supports_helper.rb
module SupportsHelper
end

workrequest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

workrequest/app/helpers/work_requests_helper.rb
module WorkRequestsHelper
end

workrequest/app/views/lookups/_form.html.erb
<%= form_for(@lookup) do |f| %>
  <% if @lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
      <% @lookup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lookup_name %><br />
    <%= f.text_field :lookup_name %>
  </div>
  <div class="field">
    <%= f.label :lookup_key %><br />
    <%= f.text_field :lookup_key %>
  </div>
  <div class="field">
    <%= f.label :lookup_value %><br />
    <%= f.text_field :lookup_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workrequest/app/views/lookups/edit.html.erb
<h1>Editing lookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

workrequest/app/views/lookups/index.html.erb
<h1>Listing lookups</h1>

<table>
  <tr>
    <th>Lookup name</th>
    <th>Lookup key</th>
    <th>Lookup value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lookups.each do |lookup| %>
  <tr>
    <td><%= lookup.lookup_name %></td>
    <td><%= lookup.lookup_key %></td>
    <td><%= lookup.lookup_value %></td>
    <td><%= link_to 'Show', lookup %></td>
    <td><%= link_to 'Edit', edit_lookup_path(lookup) %></td>
    <td><%= link_to 'Destroy', lookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lookup', new_lookup_path %>

workrequest/app/views/lookups/new.html.erb
<h1>New lookup</h1>

<%= render 'form' %>

<%= link_to 'Back', lookups_path %>

workrequest/app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lookup name:</b>
  <%= @lookup.lookup_name %>
</p>

<p>
  <b>Lookup key:</b>
  <%= @lookup.lookup_key %>
</p>

<p>
  <b>Lookup value:</b>
  <%= @lookup.lookup_value %>
</p>


<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>

workrequest/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Firstname</li>
    <li><%= f.text_field :firstname %></li>
    <li data-role="list-divider">Lastname</li>
    <li><%= f.text_field :lastname %></li>
    <li data-role="list-divider">Email</li>
    <li><%= @profile.email %></li>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workrequest/app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

workrequest/app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.firstname %></td>
    <td><%= profile.lastname %></td>
    <td><%= profile.email %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

workrequest/app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

workrequest/app/views/profiles/show.html.erb
<h1>Profile</h1>

<% if @profile.email == current_user.email %>
<div data-role="navbar">
	<ul>
		<li><%= link_to "Edit",  edit_profile_path(@profile) %></li>
	</ul>
</div>
<% end -%>

<ul data-role="listview" data-inset="true">
	<li data-role="list-divider">First name</li>
	<li><%= @profile.firstname %></li>
	<li data-role="list-divider">Last name</li>
	<li><%= @profile.lastname %></li>
	<li data-role="list-divider">Email</li>
	<li><%= @profile.email %></li>
</ul>