workrequest/config/routes.rb
Workrequest::Application.routes.draw do
  resources :companies

  resources :supports

  resources :work_requests

  resources :profiles

  get "welcome/index"

  devise_for :users

  resources :lookups

  root :to => 'welcome#index'

end

workrequest/app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :title

  default_scope order('title asc')
end

workrequest/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
  
end

workrequest/app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name
  default_scope order('name asc')

  has_many :profiles
  has_many :workrequests
  has_many :supports
end

workrequest/app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :lookup_key, :lookup_name, :lookup_value
end

workrequest/app/models/plant.rb
class Plant < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
  
end

workrequest/app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname, :company_id
  default_scope order('firstname asc')

  has_many :workrequests
  has_many :supports
  belongs_to :company

  scope :by_email, lambda {|email| where('email=?',email)}

  validates :email, :uniqueness => true
end

workrequest/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
end

workrequest/app/models/support.rb
class Support < ActiveRecord::Base
  attr_accessible :assignedto_id, :businessunit_id, :category_id, :created_by, :description, :plant_id, :queue, :status_id, :title, :workrequest_id
  has_one :businessunit
  has_one :category
  has_one :plant
  has_one :status
  has_one :workrequest
end

workrequest/app/models/support_comment.rb
class SupportComment < ActiveRecord::Base
  attr_accessible :comment, :support_id
end

workrequest/app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :title

  has_many :workrequests
  has_many :supports
end

workrequest/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

workrequest/app/models/work_request.rb
class WorkRequest < ActiveRecord::Base
  attr_accessible :area_id, :category_id, :plant_id, :queue, :requestors, :status_id, :title, :created_by, :unit_id, :company_id, :profile_id

  belongs_to :category
  belongs_to :area
  belongs_to :unit
  belongs_to :plant
  belongs_to :status
  belongs_to :company
  belongs_to :profile

  validates :title, :presence => true
  validates :area_id, :presence => true
  validates :unit_id, :presence => true
  validates :category_id, :presence => true
  validates :plant_id, :presence => true
  validates :status_id, :presence => true
  validates :requestors, :presence => true

  scope :by_company_id, lambda { |company_id| where('company_id=?', company_id)}

end

workrequest/app/models/work_request_comment.rb
class WorkRequestComment < ActiveRecord::Base
  attr_accessible :comment, :workrequest_id
end

workrequest/app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lookups }
    end
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/new
  # GET /lookups/new.json
  def new
    @lookup = Lookup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/1/edit
  def edit
    @lookup = Lookup.find(params[:id])
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(params[:lookup])

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render json: @lookup, status: :created, location: @lookup }
      else
        format.html { render action: "new" }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lookups/1
  # PUT /lookups/1.json
  def update
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      if @lookup.update_attributes(params[:lookup])
        format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup = Lookup.find(params[:id])
    @lookup.destroy

    respond_to do |format|
      format.html { redirect_to lookups_url }
      format.json { head :no_content }
    end
  end
end

workrequest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
  		@profile = Profile.by_email(current_user.email).first
  		if @profile == nil
  			@profile = Profile.new
  			@profile.email = current_user.email
  			@profile.save
  		end
  	end
  end
end

workrequest/app/controllers/work_requests_controller.rb
class WorkRequestsController < ApplicationController
  before_filter :authenticate_user!
  # GET /work_requests
  # GET /work_requests.json
  def index
    @work_requests = WorkRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_requests }
    end
  end

  # GET /work_requests/1
  # GET /work_requests/1.json
  def show
    @work_request = WorkRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_request }
    end
  end

  # GET /work_requests/new
  # GET /work_requests/new.json
  def new
    @work_request = WorkRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_request }
    end
  end

  # GET /work_requests/1/edit
  def edit
    @work_request = WorkRequest.find(params[:id])
  end

  # POST /work_requests
  # POST /work_requests.json
  def create
    @work_request = WorkRequest.new(params[:work_request])
    Rails.logger.debug "Params value: " 
    Rails.logger.debug params[:work_request]

    respond_to do |format|
      if @work_request.save
        format.html { redirect_to @work_request, notice: 'Work request was successfully created.' }
        format.json { render json: @work_request, status: :created, location: @work_request }
      else
        format.html { render action: "new" }
        format.json { render json: @work_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_requests/1
  # PUT /work_requests/1.json
  def update
    @work_request = WorkRequest.find(params[:id])

    respond_to do |format|
      if @work_request.update_attributes(params[:work_request])
        format.html { redirect_to @work_request, notice: 'Work request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_requests/1
  # DELETE /work_requests/1.json
  def destroy
    @work_request = WorkRequest.find(params[:id])
    @work_request.destroy

    respond_to do |format|
      format.html { redirect_to work_requests_url }
      format.json { head :no_content }
    end
  end
end

workrequest/app/helpers/application_helper.rb
module ApplicationHelper
end

workrequest/app/helpers/companies_helper.rb
module CompaniesHelper
end

workrequest/app/helpers/lookups_helper.rb
module LookupsHelper
end

workrequest/app/helpers/profiles_helper.rb
module ProfilesHelper
end

workrequest/app/helpers/supports_helper.rb
module SupportsHelper
end

workrequest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

workrequest/app/helpers/work_requests_helper.rb
module WorkRequestsHelper
end

workrequest/app/views/work_requests/_form.html.erb
<%= form_for(@work_request) do |f| %>
  <% if @work_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_request.errors.count, "error") %> prohibited this work request from being saved:</h2>

      <ul>
      <% @work_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Title</li>
    <li><%= f.text_field :title %></li>
    <li data-role="list-divider">Business Unit</li>
    <li><%= collection_select(:work_request, :unit_id, Unit.all, :id, :title, {:include_blank => 'Please select a business unit'}) %></li>
    <li data-role="list-divider">Category</li>
    <li><%= collection_select(:work_request, :category_id, Category.all,:id,:title ,{:include_blank => 'Please select a category'}) %></li>
    <li data-role="list-divider">Status</li>
    <li><%= collection_select(:work_request, :status_id, Status.all,:id,:title,{:include_blank => 'Please select a status'}) %></li>
    <li data-role="list-divider">Plant</li>
    <li><%=  collection_select(:work_request, :plant_id, Plant.all,:id,:title, {:include_blank => 'Please select a plant'}) %></li>
    <li data-role="list-divider">Area</li>
    <li><%= collection_select(:work_request, :area_id, Area.all,:id,:title, {:include_blank => 'Please select an area'}) %></li>
    <li data-role="list-divider">Requestors</li>
    <li><%= f.text_field :requestors %></li>
    <li data-role="list-divider">Queue</li>
    <li><%= f.text_field :queue %></li>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workrequest/app/views/work_requests/edit.html.erb
<h1>Editing work request</h1>

<%= render 'form' %>

workrequest/app/views/work_requests/index.html.erb
<h1>Listing Work Requests</h1>

<div data-role="navbar">
    <ul>
        <li><%= link_to 'New Work request', new_work_request_path %></li>
    </ul>
</div>

<ul data-role="listview" data-inset="true" >
    <% @work_requests.each do |work_request| %>
    <li><%= link_to work_request.title, work_request, :data=>{:ajax=>"false"} %></li>
    <% end %>
</ul>

workrequest/app/views/work_requests/new.html.erb
<h1>New work request</h1>

<%= render 'form' %>

workrequest/app/views/work_requests/show.html.erb
<h1>Work Request</h1>
<div data-role="navbar">
  <ul>
    <li><%= link_to "Edit", edit_work_request_path, :data=>{:icon=>"edit"} %></li>
    <li><%= link_to "List", work_requests_path, :data=>{:icon=>"grid"} %></li>
  </ul>
</div>

<ul data-role="listview" data-inset="true">
  <li data-role="list-divider">Title</li>
  <li><%= @work_request.title %></li>

  <li data-role="list-divider">Business Unit</li>
  <li><%= @work_request.unit.title %></li>

  <li data-role="list-divider">Category</li>
  <li><%= @work_request.category.title %></li>

  <li data-role="list-divider">Status</li>
  <li><%= @work_request.status.title %></li>

  <li data-role="list-divider">Plant</li>
  <li><%= @work_request.plant.title %></li>

  <li data-role="list-divider">Area</li>
  <li><%= @work_request.area.title %></li>

  <li data-role="list-divider">Requestors</li>
  <li><%= @work_request.requestors %></li>

  <li data-role="list-divider">Queue</li>
  <li><%= @work_request.queue %></li>
</ul>