workrequest/config/routes.rb
Workrequest::Application.routes.draw do
  resources :companies

  resources :supports

  resources :work_requests

  resources :profiles

  get "welcome/index"

  devise_for :users

  resources :lookups

  root :to => 'welcome#index'

end

workrequest/app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :title

  default_scope order('title asc')
end

workrequest/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
  
end

workrequest/app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name
  default_scope order('name asc')

  has_many :profiles
  has_many :workrequests
  has_many :supports
end

workrequest/app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :lookup_key, :lookup_name, :lookup_value
end

workrequest/app/models/plant.rb
class Plant < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
  
end

workrequest/app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname, :company_id
  default_scope order('firstname asc')

  has_many :workrequests
  has_many :supports
  belongs_to :company

  scope :by_email, lambda {|email| where('email=?',email)}

  validates :email, :uniqueness => true
end

workrequest/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :title
  default_scope order('title asc')
end

workrequest/app/models/support.rb
class Support < ActiveRecord::Base
  attr_accessible :assignedto_id, :businessunit_id, :category_id, :created_by, :description, :plant_id, :queue, :status_id, :title, :workrequest_id
  has_one :businessunit
  has_one :category
  has_one :plant
  has_one :status
  has_one :workrequest
end

workrequest/app/models/support_comment.rb
class SupportComment < ActiveRecord::Base
  attr_accessible :comment, :support_id
end

workrequest/app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :title

  has_many :workrequests
  has_many :supports
end

workrequest/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

workrequest/app/models/work_request.rb
class WorkRequest < ActiveRecord::Base
  attr_accessible :area_id, :category_id, :plant_id, :queue, :requestors, :status_id, :title, :created_by, :unit_id, :company_id, :profile_id

  belongs_to :category
  belongs_to :area
  belongs_to :unit
  belongs_to :plant
  belongs_to :status
  belongs_to :company
  belongs_to :profile

  validates :title, :presence => true
  validates :area_id, :presence => true
  validates :unit_id, :presence => true
  validates :category_id, :presence => true
  validates :plant_id, :presence => true
  validates :status_id, :presence => true
  validates :requestors, :presence => true

  scope :by_company_id, lambda { |company_id| where('company_id=?', company_id)}

end

workrequest/app/models/work_request_comment.rb
class WorkRequestComment < ActiveRecord::Base
  attr_accessible :comment, :workrequest_id
end

workrequest/app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lookups }
    end
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/new
  # GET /lookups/new.json
  def new
    @lookup = Lookup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lookup }
    end
  end

  # GET /lookups/1/edit
  def edit
    @lookup = Lookup.find(params[:id])
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(params[:lookup])

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render json: @lookup, status: :created, location: @lookup }
      else
        format.html { render action: "new" }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lookups/1
  # PUT /lookups/1.json
  def update
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      if @lookup.update_attributes(params[:lookup])
        format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup = Lookup.find(params[:id])
    @lookup.destroy

    respond_to do |format|
      format.html { redirect_to lookups_url }
      format.json { head :no_content }
    end
  end
end

workrequest/app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  # GET /supports
  # GET /supports.json
  def index
    @supports = Support.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @supports }
    end
  end

  # GET /supports/1
  # GET /supports/1.json
  def show
    @support = Support.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @support }
    end
  end

  # GET /supports/new
  # GET /supports/new.json
  def new
    @support = Support.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @support }
    end
  end

  # GET /supports/1/edit
  def edit
    @support = Support.find(params[:id])
  end

  # POST /supports
  # POST /supports.json
  def create
    @support = Support.new(params[:support])

    respond_to do |format|
      if @support.save
        format.html { redirect_to @support, notice: 'Support was successfully created.' }
        format.json { render json: @support, status: :created, location: @support }
      else
        format.html { render action: "new" }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /supports/1
  # PUT /supports/1.json
  def update
    @support = Support.find(params[:id])

    respond_to do |format|
      if @support.update_attributes(params[:support])
        format.html { redirect_to @support, notice: 'Support was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1
  # DELETE /supports/1.json
  def destroy
    @support = Support.find(params[:id])
    @support.destroy

    respond_to do |format|
      format.html { redirect_to supports_url }
      format.json { head :no_content }
    end
  end
end

workrequest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
  		@profile = Profile.by_email(current_user.email).first
  		if @profile == nil
  			@profile = Profile.new
  			@profile.email = current_user.email
  			@profile.save
  		end
  	end
  end
end

workrequest/app/helpers/application_helper.rb
module ApplicationHelper
end

workrequest/app/helpers/companies_helper.rb
module CompaniesHelper
end

workrequest/app/helpers/lookups_helper.rb
module LookupsHelper
end

workrequest/app/helpers/profiles_helper.rb
module ProfilesHelper
end

workrequest/app/helpers/supports_helper.rb
module SupportsHelper
end

workrequest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

workrequest/app/helpers/work_requests_helper.rb
module WorkRequestsHelper
end

workrequest/app/views/supports/_form.html.erb
<%= form_for(@support) do |f| %>
  <% if @support.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@support.errors.count, "error") %> prohibited this support from being saved:</h2>

      <ul>
      <% @support.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :workrequest_id %><br />
    <%= f.number_field :workrequest_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :assignedto_id %><br />
    <%= f.number_field :assignedto_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br />
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :plant_id %><br />
    <%= f.number_field :plant_id %>
  </div>
  <div class="field">
    <%= f.label :businessunit_id %><br />
    <%= f.number_field :businessunit_id %>
  </div>
  <div class="field">
    <%= f.label :queue %><br />
    <%= f.text_field :queue %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workrequest/app/views/supports/edit.html.erb
<h1>Editing support</h1>

<%= render 'form' %>

<%= link_to 'Show', @support %> |
<%= link_to 'Back', supports_path %>

workrequest/app/views/supports/index.html.erb
<h1>Listing supports</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Workrequest</th>
    <th>Category</th>
    <th>Assignedto</th>
    <th>Status</th>
    <th>Plant</th>
    <th>Businessunit</th>
    <th>Queue</th>
    <th>Description</th>
    <th>Created by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @supports.each do |support| %>
  <tr>
    <td><%= support.title %></td>
    <td><%= support.workrequest_id %></td>
    <td><%= support.category_id %></td>
    <td><%= support.assignedto_id %></td>
    <td><%= support.status_id %></td>
    <td><%= support.plant_id %></td>
    <td><%= support.businessunit_id %></td>
    <td><%= support.queue %></td>
    <td><%= support.description %></td>
    <td><%= support.created_by %></td>
    <td><%= link_to 'Show', support %></td>
    <td><%= link_to 'Edit', edit_support_path(support) %></td>
    <td><%= link_to 'Destroy', support, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Support', new_support_path %>

workrequest/app/views/supports/new.html.erb
<h1>New support</h1>

<%= render 'form' %>

<%= link_to 'Back', supports_path %>

workrequest/app/views/supports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @support.title %>
</p>

<p>
  <b>Workrequest:</b>
  <%= @support.workrequest_id %>
</p>

<p>
  <b>Category:</b>
  <%= @support.category_id %>
</p>

<p>
  <b>Assignedto:</b>
  <%= @support.assignedto_id %>
</p>

<p>
  <b>Status:</b>
  <%= @support.status_id %>
</p>

<p>
  <b>Plant:</b>
  <%= @support.plant_id %>
</p>

<p>
  <b>Businessunit:</b>
  <%= @support.businessunit_id %>
</p>

<p>
  <b>Queue:</b>
  <%= @support.queue %>
</p>

<p>
  <b>Description:</b>
  <%= @support.description %>
</p>

<p>
  <b>Created by:</b>
  <%= @support.created_by %>
</p>


<%= link_to 'Edit', edit_support_path(@support) %> |
<%= link_to 'Back', supports_path %>